version: "3"
services:
  mysql:
    build: ./sql_data/
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
    ports: 
      - '3307:3307'

  solr:
    image: solr:8.5
    container_name: 'solr-1'
    ports:
      - "8983:8983"
    volumes:
      - data:/var/solr
    command:
      - solr-precreate
      - gettingstarted
volumes:
  data: